### ISSUE TITLE
¿Usas software libre? ¿Sabes reconocerlo? ¿Has liberado algo?

### ISSUE THREAD

**Issue by JJ** [JJ/implementacion-eas#2]
En general, ¿qué papel juega el software libre en tu práctica científica y profesional haitual?

**Comment by Investigador** [comment]
Dado que no tengo práctica científica, poco puedo decir en ese apartado, en cambio en mi práctica habitual sí puedo hablar. Un antiguo profesor mío me decía siempre que no reinventara la rueda cada vez que tenía que construir un carro, que usara la que mejor se adaptara a mi eje. En ello el software libre me permite poder realizar trabajos complejos más rápidamente, pues mucha gente en foros de programación comparte soluciones a problemas que en algún momento se te plantean, eso ayuda mucho. si a lo anterior unimos que los kits de desarrollo libres te permiten programar cuando los recursos económicos no te permiten pagar un kit de pago, o que el OpenOffice me permite usar una suite de oficina sin tener que pagar por ello, que con Linux puedo montar mi propio equipo (suelo usar versiones LTS cuando me pica la curiosidad de algo nuevo), para investigar (mi última prueba es intentar montar un servidor de correo propio con una versión Ubuntu 12.04.3 LTS en Azure, con el servidor de correo Courier, todavía no está operativo por cuestiones de tiempo, eso y que mi mujer me ha amenazado con tirarme a mi y a las torres por la ventana como ponga más "cacharros" en la habitación de estudio) pues nos podemos hacer una idea de la importancia que tiene para mí el software libre, profesionalmente en mi trabajo no se usa software libre, al menso hasta ahora, aunque parece que la tendencia puede empezar a cambiar con la siguiente generación de equipos.

**Comment by deantares** [comment]
Debido a mi trabajo uso diariamente software Libre. Uso un Sistema Operativo Libre, con entornos de desarrollo libres, haciendo uso de lenguajes de programación libres, con librerías libres, software (científico, matemático, ofimático,..) libre, uso repositorios libres... Vamos, que estoy todo el día usando software libre.

**Comment by JJ** [comment]
@deantares ¿lo usas exclusivamente?

**Comment by deantares** [comment]
Para temas de trabajo, normalmente no. Aún suelo recurrir a MS Office cuando no tengo otro remedio por la burocracia. Para ocio, ya es otro tema. O incluso en el móvil, la mayoría de las aplicaciones que uso no son libres.

**Comment by JJ** [comment]
@deantares el móvil es la quinta columna del software privativo...

**Comment by unintendedbear** [comment]
Con decir que una de las últimas cosas que he hecho ha sido no solo instalar Linux en mi PC, sino que en vez de hacerlo en una partición, borré Windows 8 con una sonrisa de oreja a oreja. Así, con ganas.
Además en el trabajo uso Linux, y los trabajos del máster los hago en LaTeX y los entrego en PDF.
Mi trabajo de fin de máster también está en un reposito de git.

**Comment by seiya64** [comment]
Por lo general suelo usar software libre o no, dependiendo de lo que quiera hacer. Para trabajar sí. Para el ocio normalmente no.

Tengo un par de cosillas liberadas aquí. Aunque acabo de darme cuenta de que los barquitos no están xD

**Comment by JJ** [comment]
@seiya64 ¿qué le ha pasado a los barquitos?
@unintendedbear así se hace :+1:

**Comment by rotty11** [comment]
Yo uso software libre "fifty fifty". Todo depende del uso que le demos a cada uno. Al igual que Antonio uso Microsoft office porque libre office no me convence (comportamientos extraños en cuanto a crear viñetas y algunas cosillas más). Si quiero programar obviamente uso librerías, IDEs, repositorios, compiladores y demás que sean software libre en la medida de lo posible dado que me encanta usarlos y no tengo por qué pagar, y si detecto un error, lo notifico y alguien lo modificará sin ánimo de lucro. El software libre, para usuarios medios-altos y programadores, es una auténtica maravilla. Ahora bien, soy de los que cuando el tiempo y aburrimiento me lo permite, me gusta echarme una partida a algo más que un SuperTux, así que tiro de Windows para poder ejecutar juegos más comerciales, ya me entendeis. Otro punto a favor de Windows es la reproducción de videos... los códecs libres en Linux me tienen frito dado que fallan bastante si mueves con frecuencia el deslizador de avance del tiempo e incluso tiene menos precisión que en Windows. Algo vital para mí cuando estoy componiendo mis videos con la guitarra flamenca dado que necesito ver unos segundos determinados 60 veces para determinar errores.
Por último, odio Apple y los pijos que le rodean. Lo considero una mancha a Linux dado que ha sido una modificación y privatización de este. Aún así, Android no es del todo libre dado que, aunque el código de las versiones 1 y 2 está liberado, contiene ejecutables privativos y no libres que provoca que en ausencia de ellos, un dispositivo no funcionase:

http://www.muycomputer.com/2011/09/20/android-realmente-libre-richard-stallman-dice-no

**Comment by pablopaolus** [comment]
Lo cierto es que, en general, no suelo utilizar software libre en mi día a día, aunque con algunas excepciones. En el trabajo utilizo Windows, y en mi portátil personal tampoco he dado el salto a Linux (aunque a veces me tienta, porque Windows acaba con la paciencia de cualquiera en muchos casos...). Sí es cierto que el Word lo dejé de utilizar hace tiempo porque es odioso. En su lugar utilizo, sobre todo, LaTeX. 
Por otro lado, cuando necesito un programa para cualquier cosa en momentos puntuales (por ej., grabación de discos) me decanto por buscar opciones de software libre.

**Comment by Investigador** [comment]
Bueno siempre nos queda un buen "rooteado" al android y con paciencia (muchas horas y la comunidad de la red) se consiguen cosillas , eso sí, solo recomendable para móviles no de última generación y fuera de garantía, ya me entendeis XD.

**Comment by JJ** [comment]
@Investigador de hecho, conozco a gente que lo hace con sus móviles de día a día, para meterle las últimas ROM "cocinadas" (que, por cierto, están en GitHub)

**Comment by Investigador** [comment]
Yo desde que tengo android, pocas veces he tenido la rom original una vez que expiraba la garantía (bueno si er a mi movil y no el de mi mujer, incluso antes de que expirase), para los que hacemos estas cosas, lo más importante es una copia guardada en 7 sitios y bajo 7 llaves de la rom original, tal cual salió de fábrica. Cuando he rooteado algún móvil, principlamente era con la intención de quitarle la "porquería" que le menten cuando no es libre de origen (e incluso cuando te lo dan libre le meten cada castaña a la rom, que en fin..). Si de paso se libera, pues mira, auqnue hoy en día lo están complicando mucho más para liberar por código, todavía me acuerdo de los Samsung Galaxy S2 y S3, que con un editor hexadecimal y sabiendo donde buscar cambiabas un 1 por un 0 y ya lo tenías liberado (mientras no actualizases el fw), eso lo haces tal cual ahora y te cargas el móvil, y si no tienes la copia de la carpeta EFS, pues tienes una fantastica pda con wifi, pero te puedes olvidar de llamar con ese móvil.
